import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

const predefinedTemplates = [
  {
    id: "template_sprint_planning",
    name: "🏃 Sprint Planning",
    description: "Organize your team's sprint with backlog, current sprint, in progress, and completed tasks. Perfect for Scrum teams.",
    category: "sprint",
    icon: "🏃",
    coverImage: "linear-gradient(135deg, #667eea 0%, #764ba2 100%)",
    isPredefined: true,
    isPublic: true,
    usageCount: 0,
    rating: 0,
    variables: JSON.stringify(["{{date}}", "{{assignee}}"]),
    lists: [
      {
        id: "list_sprint_backlog",
        name: "📋 Backlog",
        position: 0,
        color: "#94a3b8",
        emoji: "📋",
        tasks: [
          {
            id: "task_sprint_1",
            title: "User Story: {{assignee}} login",
            description: "As a user, I want to login so that I can access my account.",
            position: 0,
            emoji: "👤",
            coverColor: "#3b82f6",
            labels: JSON.stringify(["user-story", "high-priority"]),
            variables: JSON.stringify({ assignee: "{{assignee}}" }),
          },
          {
            id: "task_sprint_2",
            title: "Bug: Fix responsive design",
            description: "Mobile layout breaks on small screens.",
            position: 1,
            emoji: "🐛",
            coverColor: "#ef4444",
            labels: JSON.stringify(["bug", "ui"]),
          },
        ],
      },
      {
        id: "list_sprint_current",
        name: "🎯 Current Sprint",
        position: 1,
        color: "#3b82f6",
        emoji: "🎯",
        tasks: [
          {
            id: "task_sprint_3",
            title: "Implement authentication API",
            description: "Build JWT-based authentication endpoint.",
            position: 0,
            emoji: "🔐",
            coverColor: "#8b5cf6",
            labels: JSON.stringify(["feature", "backend"]),
          },
        ],
      },
      {
        id: "list_sprint_progress",
        name: "⚡ In Progress",
        position: 2,
        color: "#f59e0b",
        emoji: "⚡",
        tasks: [
          {
            id: "task_sprint_4",
            title: "Design homepage mockup",
            description: "Create Figma designs for landing page.",
            position: 0,
            emoji: "🎨",
            coverColor: "#ec4899",
            labels: JSON.stringify(["design", "frontend"]),
          },
        ],
      },
      {
        id: "list_sprint_done",
        name: "✅ Done",
        position: 3,
        color: "#10b981",
        emoji: "✅",
        tasks: [
          {
            id: "task_sprint_5",
            title: "Setup project repository",
            description: "Initialize Git repo and project structure.",
            position: 0,
            emoji: "📦",
            coverColor: "#059669",
            labels: JSON.stringify(["setup"]),
          },
        ],
      },
    ],
  },
  {
    id: "template_product_roadmap",
    name: "🗺️ Product Roadmap",
    description: "Plan your product development across quarters. Track features from ideation to release with Q1-Q4 organization.",
    category: "roadmap",
    icon: "🗺️",
    coverImage: "linear-gradient(135deg, #f093fb 0%, #f5576c 100%)",
    isPredefined: true,
    isPublic: true,
    usageCount: 0,
    rating: 0,
    variables: JSON.stringify(["{{date}}", "{{organization}}"]),
    lists: [
      {
        id: "list_roadmap_ideas",
        name: "💡 Ideas",
        position: 0,
        color: "#fbbf24",
        emoji: "💡",
        tasks: [
          {
            id: "task_roadmap_1",
            title: "AI-powered recommendations",
            description: "Explore ML models for personalized content.",
            position: 0,
            emoji: "🤖",
            coverColor: "#6366f1",
            labels: JSON.stringify(["research", "ai"]),
          },
        ],
      },
      {
        id: "list_roadmap_q1",
        name: "Q1 {{date}}",
        position: 1,
        color: "#3b82f6",
        emoji: "1️⃣",
        tasks: [
          {
            id: "task_roadmap_2",
            title: "Launch mobile app v1.0",
            description: "Release iOS and Android apps to stores.",
            position: 0,
            emoji: "📱",
            coverColor: "#0ea5e9",
            labels: JSON.stringify(["mobile", "launch"]),
            variables: JSON.stringify({ date: "{{date}}" }),
          },
        ],
      },
      {
        id: "list_roadmap_q2",
        name: "Q2 {{date}}",
        position: 2,
        color: "#8b5cf6",
        emoji: "2️⃣",
        tasks: [
          {
            id: "task_roadmap_3",
            title: "Team collaboration features",
            description: "Real-time editing and comments for {{organization}}.",
            position: 0,
            emoji: "👥",
            coverColor: "#a855f7",
            labels: JSON.stringify(["collaboration", "feature"]),
            variables: JSON.stringify({ organization: "{{organization}}" }),
          },
        ],
      },
      {
        id: "list_roadmap_q3",
        name: "Q3 {{date}}",
        position: 3,
        color: "#ec4899",
        emoji: "3️⃣",
        tasks: [
          {
            id: "task_roadmap_4",
            title: "Enterprise SSO integration",
            description: "Support SAML and OAuth for enterprise clients.",
            position: 0,
            emoji: "🔐",
            coverColor: "#db2777",
            labels: JSON.stringify(["enterprise", "security"]),
          },
        ],
      },
      {
        id: "list_roadmap_q4",
        name: "Q4 {{date}}",
        position: 4,
        color: "#10b981",
        emoji: "4️⃣",
        tasks: [
          {
            id: "task_roadmap_5",
            title: "Analytics dashboard",
            description: "User behavior insights and metrics.",
            position: 0,
            emoji: "📊",
            coverColor: "#059669",
            labels: JSON.stringify(["analytics", "feature"]),
          },
        ],
      },
    ],
  },
  {
    id: "template_content_calendar",
    name: "📅 Content Calendar",
    description: "Manage your content pipeline from ideation to publication. Perfect for marketing teams and content creators.",
    category: "calendar",
    icon: "📅",
    coverImage: "linear-gradient(135deg, #fa709a 0%, #fee140 100%)",
    isPredefined: true,
    isPublic: true,
    usageCount: 0,
    rating: 0,
    variables: JSON.stringify(["{{date}}", "{{assignee}}"]),
    lists: [
      {
        id: "list_content_ideas",
        name: "💭 Content Ideas",
        position: 0,
        color: "#fbbf24",
        emoji: "💭",
        tasks: [
          {
            id: "task_content_1",
            title: "Blog: 10 Tips for Remote Work",
            description: "Interview team members about their remote work setups.",
            position: 0,
            emoji: "✍️",
            coverColor: "#f59e0b",
            labels: JSON.stringify(["blog", "remote-work"]),
          },
          {
            id: "task_content_2",
            title: "Video: Product Demo",
            description: "Short explainer video for new features.",
            position: 1,
            emoji: "🎥",
            coverColor: "#ef4444",
            labels: JSON.stringify(["video", "product"]),
          },
        ],
      },
      {
        id: "list_content_drafts",
        name: "📝 Drafts",
        position: 1,
        color: "#3b82f6",
        emoji: "📝",
        tasks: [
          {
            id: "task_content_3",
            title: "Newsletter: Monthly Update - {{date}}",
            description: "Highlight new features and customer stories.",
            position: 0,
            emoji: "📧",
            coverColor: "#3b82f6",
            labels: JSON.stringify(["newsletter", "email"]),
            variables: JSON.stringify({ date: "{{date}}" }),
          },
        ],
      },
      {
        id: "list_content_review",
        name: "👀 In Review",
        position: 2,
        color: "#8b5cf6",
        emoji: "👀",
        tasks: [
          {
            id: "task_content_4",
            title: "Social: Product Launch Announcement",
            description: "Twitter thread + LinkedIn post. Assigned to {{assignee}}.",
            position: 0,
            emoji: "📣",
            coverColor: "#6366f1",
            labels: JSON.stringify(["social-media", "launch"]),
            variables: JSON.stringify({ assignee: "{{assignee}}" }),
          },
        ],
      },
      {
        id: "list_content_scheduled",
        name: "📅 Scheduled",
        position: 3,
        color: "#f59e0b",
        emoji: "📅",
        tasks: [
          {
            id: "task_content_5",
            title: "Blog: Case Study with ABC Corp",
            description: "Publish on {{date}} at 10am EST.",
            position: 0,
            emoji: "📖",
            coverColor: "#d97706",
            labels: JSON.stringify(["blog", "case-study"]),
            variables: JSON.stringify({ date: "{{date}}" }),
          },
        ],
      },
      {
        id: "list_content_published",
        name: "✅ Published",
        position: 4,
        color: "#10b981",
        emoji: "✅",
        tasks: [
          {
            id: "task_content_6",
            title: "Video: Customer Testimonials",
            description: "Published on YouTube and LinkedIn.",
            position: 0,
            emoji: "⭐",
            coverColor: "#059669",
            labels: JSON.stringify(["video", "testimonial"]),
          },
        ],
      },
    ],
  },
  {
    id: "template_bug_tracking",
    name: "🐛 Bug Tracking",
    description: "Track and resolve bugs efficiently. From reporting to resolution with priority-based workflow.",
    category: "bugtracking",
    icon: "🐛",
    coverImage: "linear-gradient(135deg, #ff9a9e 0%, #fecfef 100%)",
    isPredefined: true,
    isPublic: true,
    usageCount: 0,
    rating: 0,
    variables: JSON.stringify(["{{assignee}}"]),
    lists: [
      {
        id: "list_bug_reported",
        name: "📝 Reported",
        position: 0,
        color: "#94a3b8",
        emoji: "📝",
        tasks: [
          {
            id: "task_bug_1",
            title: "Login button not responsive",
            description: "Button doesn't work on Safari iOS 15.",
            position: 0,
            emoji: "🔴",
            coverColor: "#ef4444",
            labels: JSON.stringify(["critical", "frontend"]),
          },
          {
            id: "task_bug_2",
            title: "Profile image upload fails",
            description: "Error 500 when uploading PNG files > 2MB.",
            position: 1,
            emoji: "🟡",
            coverColor: "#f59e0b",
            labels: JSON.stringify(["medium", "backend"]),
          },
        ],
      },
      {
        id: "list_bug_triaged",
        name: "🔍 Triaged",
        position: 1,
        color: "#3b82f6",
        emoji: "🔍",
        tasks: [
          {
            id: "task_bug_3",
            title: "Search results pagination broken",
            description: "Page 3+ returns empty results. Assigned to {{assignee}}.",
            position: 0,
            emoji: "🟠",
            coverColor: "#fb923c",
            labels: JSON.stringify(["high", "search"]),
            variables: JSON.stringify({ assignee: "{{assignee}}" }),
          },
        ],
      },
      {
        id: "list_bug_progress",
        name: "⚡ In Progress",
        position: 2,
        color: "#8b5cf6",
        emoji: "⚡",
        tasks: [
          {
            id: "task_bug_4",
            title: "Dashboard loads slowly",
            description: "Optimizing database queries for performance.",
            position: 0,
            emoji: "🟢",
            coverColor: "#a855f7",
            labels: JSON.stringify(["low", "performance"]),
          },
        ],
      },
      {
        id: "list_bug_testing",
        name: "🧪 Testing",
        position: 3,
        color: "#f59e0b",
        emoji: "🧪",
        tasks: [
          {
            id: "task_bug_5",
            title: "Email notifications not sending",
            description: "Fixed SMTP config, testing across providers.",
            position: 0,
            emoji: "🔴",
            coverColor: "#dc2626",
            labels: JSON.stringify(["critical", "email"]),
          },
        ],
      },
      {
        id: "list_bug_resolved",
        name: "✅ Resolved",
        position: 4,
        color: "#10b981",
        emoji: "✅",
        tasks: [
          {
            id: "task_bug_6",
            title: "Dark mode toggle glitch",
            description: "Fixed theme persistence in localStorage.",
            position: 0,
            emoji: "🟢",
            coverColor: "#059669",
            labels: JSON.stringify(["low", "ui"]),
          },
        ],
      },
    ],
  },
  {
    id: "template_onboarding",
    name: "🎓 Employee Onboarding",
    description: "Streamline new hire onboarding with pre-start tasks, weekly milestones, and completion tracking.",
    category: "onboarding",
    icon: "🎓",
    coverImage: "linear-gradient(135deg, #a8edea 0%, #fed6e3 100%)",
    isPredefined: true,
    isPublic: true,
    usageCount: 0,
    rating: 0,
    variables: JSON.stringify(["{{assignee}}", "{{date}}", "{{organization}}"]),
    lists: [
      {
        id: "list_onboard_prestart",
        name: "📋 Pre-Start",
        position: 0,
        color: "#94a3b8",
        emoji: "📋",
        tasks: [
          {
            id: "task_onboard_1",
            title: "Send offer letter to {{assignee}}",
            description: "Include salary, benefits, start date {{date}}.",
            position: 0,
            emoji: "📄",
            coverColor: "#64748b",
            labels: JSON.stringify(["hr", "documents"]),
            variables: JSON.stringify({ assignee: "{{assignee}}", date: "{{date}}" }),
          },
          {
            id: "task_onboard_2",
            title: "Setup laptop and accounts",
            description: "Email, Slack, GitHub, AWS access for {{organization}}.",
            position: 1,
            emoji: "💻",
            coverColor: "#475569",
            labels: JSON.stringify(["it", "setup"]),
            variables: JSON.stringify({ organization: "{{organization}}" }),
          },
        ],
      },
      {
        id: "list_onboard_week1",
        name: "1️⃣ Week 1",
        position: 1,
        color: "#3b82f6",
        emoji: "1️⃣",
        tasks: [
          {
            id: "task_onboard_3",
            title: "Orientation: Company culture & values",
            description: "Meet with HR and team leads.",
            position: 0,
            emoji: "🏢",
            coverColor: "#3b82f6",
            labels: JSON.stringify(["orientation", "culture"]),
          },
          {
            id: "task_onboard_4",
            title: "Setup development environment",
            description: "Clone repos, install tools, run hello world.",
            position: 1,
            emoji: "⚙️",
            coverColor: "#2563eb",
            labels: JSON.stringify(["technical", "setup"]),
          },
        ],
      },
      {
        id: "list_onboard_week2",
        name: "2️⃣ Week 2",
        position: 2,
        color: "#8b5cf6",
        emoji: "2️⃣",
        tasks: [
          {
            id: "task_onboard_5",
            title: "Shadow team members",
            description: "Pair programming sessions and code reviews.",
            position: 0,
            emoji: "👥",
            coverColor: "#7c3aed",
            labels: JSON.stringify(["mentorship", "learning"]),
          },
          {
            id: "task_onboard_6",
            title: "First small task assignment",
            description: "Pick up a good-first-issue from backlog.",
            position: 1,
            emoji: "🎯",
            coverColor: "#6d28d9",
            labels: JSON.stringify(["task", "beginner"]),
          },
        ],
      },
      {
        id: "list_onboard_month1",
        name: "📅 30-Day Check-in",
        position: 3,
        color: "#f59e0b",
        emoji: "📅",
        tasks: [
          {
            id: "task_onboard_7",
            title: "1-on-1 with manager",
            description: "Feedback on first month, address concerns.",
            position: 0,
            emoji: "💬",
            coverColor: "#d97706",
            labels: JSON.stringify(["feedback", "management"]),
          },
        ],
      },
      {
        id: "list_onboard_complete",
        name: "✅ Completed",
        position: 4,
        color: "#10b981",
        emoji: "✅",
        tasks: [
          {
            id: "task_onboard_8",
            title: "Onboarding survey",
            description: "Collect feedback to improve process.",
            position: 0,
            emoji: "📊",
            coverColor: "#059669",
            labels: JSON.stringify(["feedback", "survey"]),
          },
        ],
      },
    ],
  },
  {
    id: "template_event_planning",
    name: "🎉 Event Planning",
    description: "Plan successful events from concept to execution. Track vendors, promotion, and day-of logistics.",
    category: "event",
    icon: "🎉",
    coverImage: "linear-gradient(135deg, #ffecd2 0%, #fcb69f 100%)",
    isPredefined: true,
    isPublic: true,
    usageCount: 0,
    rating: 0,
    variables: JSON.stringify(["{{date}}", "{{assignee}}"]),
    lists: [
      {
        id: "list_event_planning",
        name: "📝 Planning",
        position: 0,
        color: "#94a3b8",
        emoji: "📝",
        tasks: [
          {
            id: "task_event_1",
            title: "Define event goals & budget",
            description: "Conference for 200 attendees on {{date}}.",
            position: 0,
            emoji: "🎯",
            coverColor: "#64748b",
            labels: JSON.stringify(["planning", "budget"]),
            variables: JSON.stringify({ date: "{{date}}" }),
          },
          {
            id: "task_event_2",
            title: "Book venue",
            description: "Downtown convention center, capacity 250.",
            position: 1,
            emoji: "🏛️",
            coverColor: "#475569",
            labels: JSON.stringify(["venue", "logistics"]),
          },
        ],
      },
      {
        id: "list_event_vendors",
        name: "🤝 Vendors",
        position: 1,
        color: "#3b82f6",
        emoji: "🤝",
        tasks: [
          {
            id: "task_event_3",
            title: "Catering - contact {{assignee}}",
            description: "Vegetarian/vegan options, dietary restrictions.",
            position: 0,
            emoji: "🍽️",
            coverColor: "#3b82f6",
            labels: JSON.stringify(["catering", "vendor"]),
            variables: JSON.stringify({ assignee: "{{assignee}}" }),
          },
          {
            id: "task_event_4",
            title: "AV equipment rental",
            description: "Projector, mics, speakers, lighting.",
            position: 1,
            emoji: "🎤",
            coverColor: "#2563eb",
            labels: JSON.stringify(["av", "vendor"]),
          },
        ],
      },
      {
        id: "list_event_promo",
        name: "📣 Promotion",
        position: 2,
        color: "#8b5cf6",
        emoji: "📣",
        tasks: [
          {
            id: "task_event_5",
            title: "Launch event website",
            description: "Registration page with Stripe integration.",
            position: 0,
            emoji: "🌐",
            coverColor: "#7c3aed",
            labels: JSON.stringify(["website", "marketing"]),
          },
          {
            id: "task_event_6",
            title: "Social media campaign",
            description: "Countdown posts, speaker announcements.",
            position: 1,
            emoji: "📱",
            coverColor: "#6d28d9",
            labels: JSON.stringify(["social", "marketing"]),
          },
        ],
      },
      {
        id: "list_event_dayof",
        name: "🎪 Day-Of",
        position: 3,
        color: "#f59e0b",
        emoji: "🎪",
        tasks: [
          {
            id: "task_event_7",
            title: "Setup: Registration desk",
            description: "Name tags, swag bags, check-in tablets.",
            position: 0,
            emoji: "✅",
            coverColor: "#d97706",
            labels: JSON.stringify(["setup", "logistics"]),
          },
          {
            id: "task_event_8",
            title: "Coordinate speakers",
            description: "Greenroom, mic checks, schedule reminders.",
            position: 1,
            emoji: "🎤",
            coverColor: "#ea580c",
            labels: JSON.stringify(["speakers", "coordination"]),
          },
        ],
      },
      {
        id: "list_event_followup",
        name: "📧 Follow-up",
        position: 4,
        color: "#10b981",
        emoji: "📧",
        tasks: [
          {
            id: "task_event_9",
            title: "Send thank you emails",
            description: "Attendees, speakers, sponsors, vendors.",
            position: 0,
            emoji: "💌",
            coverColor: "#059669",
            labels: JSON.stringify(["email", "gratitude"]),
          },
          {
            id: "task_event_10",
            title: "Post-event survey",
            description: "Collect feedback for future improvements.",
            position: 1,
            emoji: "📊",
            coverColor: "#047857",
            labels: JSON.stringify(["feedback", "survey"]),
          },
        ],
      },
    ],
  },
];

async function main() {
  console.log("🌱 Seeding predefined board templates...");

  for (const template of predefinedTemplates) {
    const { lists, ...templateData } = template;

    console.log(`   Creating template: ${template.name}`);

    await prisma.boardTemplate.create({
      data: {
        ...templateData,
        lists: {
          create: lists.map((list) => {
            const { tasks, ...listData } = list;
            return {
              ...listData,
              tasks: {
                create: tasks,
              },
            };
          }),
        },
      },
    });
  }

  console.log("✅ Successfully seeded 6 predefined templates!");
}

main()
  .catch((e) => {
    console.error("❌ Error seeding templates:", e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
