import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

const additionalTemplates = [
  {
    id: "template_social_media_calendar",
    name: "📱 Social Media Calendar",
    description: "Plan your social media posts across platforms with weekly organization and approval workflow.",
    category: "calendar",
    icon: "📱",
    coverImage: "linear-gradient(135deg, #667eea 0%, #764ba2 100%)",
    isPredefined: true,
    isPublic: true,
    usageCount: 0,
    rating: 0,
    variables: JSON.stringify(["{{date}}"]),
    lists: [
      {
        id: "list_social_monday",
        name: "📅 Monday {{date}}",
        position: 0,
        color: "#3b82f6",
        emoji: "📅",
        tasks: [
          {
            id: "task_social_1",
            title: "🐦 Twitter: Morning motivation quote",
            description: "Post at 9AM EST. Include brand hashtag.",
            position: 0,
            emoji: "🐦",
            coverColor: "#1da1f2",
            labels: JSON.stringify(["twitter", "scheduled"]),
          },
          {
            id: "task_social_2",
            title: "📘 Facebook: Product showcase",
            description: "Highlight feature with demo video.",
            position: 1,
            emoji: "📘",
            coverColor: "#1877f2",
            labels: JSON.stringify(["facebook", "video"]),
          },
        ],
      },
      {
        id: "list_social_tuesday",
        name: "📅 Tuesday {{date}}",
        position: 1,
        color: "#8b5cf6",
        emoji: "📅",
        tasks: [
          {
            id: "task_social_3",
            title: "💼 LinkedIn: Industry insights",
            description: "Share article with professional commentary.",
            position: 0,
            emoji: "💼",
            coverColor: "#0a66c2",
            labels: JSON.stringify(["linkedin", "article"]),
          },
        ],
      },
      {
        id: "list_social_wednesday",
        name: "📅 Wednesday {{date}}",
        position: 2,
        color: "#ec4899",
        emoji: "📅",
        tasks: [
          {
            id: "task_social_4",
            title: "📸 Instagram: Behind the scenes",
            description: "Team photo from office. Use Stories + Feed.",
            position: 0,
            emoji: "📸",
            coverColor: "#e1306c",
            labels: JSON.stringify(["instagram", "photo"]),
          },
        ],
      },
      {
        id: "list_social_thursday",
        name: "📅 Thursday {{date}}",
        position: 3,
        color: "#f59e0b",
        emoji: "📅",
        tasks: [
          {
            id: "task_social_5",
            title: "🎥 TikTok: Quick tutorial",
            description: "15-second how-to video with trending audio.",
            position: 0,
            emoji: "🎥",
            coverColor: "#000000",
            labels: JSON.stringify(["tiktok", "video"]),
          },
        ],
      },
      {
        id: "list_social_friday",
        name: "📅 Friday {{date}}",
        position: 4,
        color: "#10b981",
        emoji: "📅",
        tasks: [
          {
            id: "task_social_6",
            title: "🎉 All platforms: Weekend vibes",
            description: "Fun, engaging content to end the week.",
            position: 0,
            emoji: "🎉",
            coverColor: "#6366f1",
            labels: JSON.stringify(["all-platforms", "engagement"]),
          },
        ],
      },
    ],
  },
  {
    id: "template_design_portfolio",
    name: "🎨 Design Portfolio",
    description: "Organize design projects by status with client feedback and revision tracking.",
    category: "custom",
    icon: "🎨",
    coverImage: "linear-gradient(135deg, #f093fb 0%, #f5576c 100%)",
    isPredefined: true,
    isPublic: true,
    usageCount: 0,
    rating: 0,
    variables: JSON.stringify(["{{assignee}}"]),
    lists: [
      {
        id: "list_design_concepts",
        name: "💡 Concepts",
        position: 0,
        color: "#fbbf24",
        emoji: "💡",
        tasks: [
          {
            id: "task_design_1",
            title: "🌟 Brand identity for startup",
            description: "Logo, color palette, typography exploration.",
            position: 0,
            emoji: "🌟",
            coverColor: "#f59e0b",
            labels: JSON.stringify(["branding", "new-client"]),
          },
          {
            id: "task_design_2",
            title: "📱 Mobile app UI redesign",
            description: "Modern, clean interface for iOS and Android.",
            position: 1,
            emoji: "📱",
            coverColor: "#3b82f6",
            labels: JSON.stringify(["ui-design", "mobile"]),
          },
        ],
      },
      {
        id: "list_design_progress",
        name: "⚡ In Progress",
        position: 1,
        color: "#3b82f6",
        emoji: "⚡",
        tasks: [
          {
            id: "task_design_3",
            title: "🎭 Website mockups - Homepage",
            description: "Responsive designs for desktop, tablet, mobile. Assigned to {{assignee}}.",
            position: 0,
            emoji: "🎭",
            coverColor: "#6366f1",
            labels: JSON.stringify(["web-design", "mockups"]),
            variables: JSON.stringify({ assignee: "{{assignee}}" }),
          },
        ],
      },
      {
        id: "list_design_review",
        name: "👀 Client Review",
        position: 2,
        color: "#8b5cf6",
        emoji: "👀",
        tasks: [
          {
            id: "task_design_4",
            title: "🖼️ Social media templates",
            description: "Instagram, Facebook, LinkedIn post templates.",
            position: 0,
            emoji: "🖼️",
            coverColor: "#a855f7",
            labels: JSON.stringify(["social", "templates"]),
          },
        ],
      },
      {
        id: "list_design_revisions",
        name: "🔄 Revisions",
        position: 3,
        color: "#f59e0b",
        emoji: "🔄",
        tasks: [
          {
            id: "task_design_5",
            title: "📊 Dashboard UI - Round 2",
            description: "Update color scheme per client feedback.",
            position: 0,
            emoji: "📊",
            coverColor: "#d97706",
            labels: JSON.stringify(["ui-design", "revision"]),
          },
        ],
      },
      {
        id: "list_design_delivered",
        name: "✅ Delivered",
        position: 4,
        color: "#10b981",
        emoji: "✅",
        tasks: [
          {
            id: "task_design_6",
            title: "🎪 Event poster design",
            description: "Final files delivered in PNG, SVG, PDF.",
            position: 0,
            emoji: "🎪",
            coverColor: "#059669",
            labels: JSON.stringify(["print", "delivered"]),
          },
        ],
      },
    ],
  },
  {
    id: "template_product_launch",
    name: "🚀 Product Launch",
    description: "Coordinate all aspects of a product launch from pre-launch to post-launch activities.",
    category: "roadmap",
    icon: "🚀",
    coverImage: "linear-gradient(135deg, #fa709a 0%, #fee140 100%)",
    isPredefined: true,
    isPublic: true,
    usageCount: 0,
    rating: 0,
    variables: JSON.stringify(["{{date}}", "{{organization}}"]),
    lists: [
      {
        id: "list_launch_prelaunch",
        name: "🎯 Pre-Launch (4 weeks)",
        position: 0,
        color: "#3b82f6",
        emoji: "🎯",
        tasks: [
          {
            id: "task_launch_1",
            title: "📝 Create landing page",
            description: "Build waitlist page with email signup for {{organization}}.",
            position: 0,
            emoji: "📝",
            coverColor: "#3b82f6",
            labels: JSON.stringify(["website", "high-priority"]),
            variables: JSON.stringify({ organization: "{{organization}}" }),
          },
          {
            id: "task_launch_2",
            title: "🎥 Record demo video",
            description: "2-minute explainer showing key features.",
            position: 1,
            emoji: "🎥",
            coverColor: "#6366f1",
            labels: JSON.stringify(["video", "content"]),
          },
          {
            id: "task_launch_3",
            title: "📧 Email sequence setup",
            description: "5-email drip campaign for waitlist subscribers.",
            position: 2,
            emoji: "📧",
            coverColor: "#8b5cf6",
            labels: JSON.stringify(["email", "marketing"]),
          },
        ],
      },
      {
        id: "list_launch_week",
        name: "🔥 Launch Week",
        position: 1,
        color: "#f59e0b",
        emoji: "🔥",
        tasks: [
          {
            id: "task_launch_4",
            title: "🎊 Launch Day - {{date}}",
            description: "Go live on Product Hunt, Hacker News, Twitter.",
            position: 0,
            emoji: "🎊",
            coverColor: "#f59e0b",
            labels: JSON.stringify(["launch", "critical"]),
            variables: JSON.stringify({ date: "{{date}}" }),
          },
          {
            id: "task_launch_5",
            title: "📣 Press release distribution",
            description: "Send to TechCrunch, VentureBeat, tech media.",
            position: 1,
            emoji: "📣",
            coverColor: "#ea580c",
            labels: JSON.stringify(["pr", "media"]),
          },
          {
            id: "task_launch_6",
            title: "💬 Live Q&A session",
            description: "Host AMA on Reddit or Twitter Spaces.",
            position: 2,
            emoji: "💬",
            coverColor: "#dc2626",
            labels: JSON.stringify(["community", "engagement"]),
          },
        ],
      },
      {
        id: "list_launch_postlaunch",
        name: "📊 Post-Launch (2 weeks)",
        position: 2,
        color: "#8b5cf6",
        emoji: "📊",
        tasks: [
          {
            id: "task_launch_7",
            title: "📈 Analyze launch metrics",
            description: "Signups, traffic, conversion rates, feedback.",
            position: 0,
            emoji: "📈",
            coverColor: "#7c3aed",
            labels: JSON.stringify(["analytics", "reporting"]),
          },
          {
            id: "task_launch_8",
            title: "🐛 Bug fixes & quick wins",
            description: "Address critical issues from user feedback.",
            position: 1,
            emoji: "🐛",
            coverColor: "#6d28d9",
            labels: JSON.stringify(["development", "hotfix"]),
          },
          {
            id: "task_launch_9",
            title: "💌 Thank you campaign",
            description: "Email early adopters with special offers.",
            position: 2,
            emoji: "💌",
            coverColor: "#5b21b6",
            labels: JSON.stringify(["email", "retention"]),
          },
        ],
      },
      {
        id: "list_launch_ongoing",
        name: "🔄 Ongoing Marketing",
        position: 3,
        color: "#10b981",
        emoji: "🔄",
        tasks: [
          {
            id: "task_launch_10",
            title: "✍️ Blog post series",
            description: "Use cases, tutorials, customer stories.",
            position: 0,
            emoji: "✍️",
            coverColor: "#059669",
            labels: JSON.stringify(["content", "seo"]),
          },
          {
            id: "task_launch_11",
            title: "🎙️ Podcast tour",
            description: "Reach out to 10 relevant podcasts.",
            position: 1,
            emoji: "🎙️",
            coverColor: "#047857",
            labels: JSON.stringify(["pr", "podcasts"]),
          },
        ],
      },
    ],
  },
  {
    id: "template_research_study",
    name: "🔬 Research Study",
    description: "Manage academic or market research projects from literature review to publication.",
    category: "custom",
    icon: "🔬",
    coverImage: "linear-gradient(135deg, #a8edea 0%, #fed6e3 100%)",
    isPredefined: true,
    isPublic: true,
    usageCount: 0,
    rating: 0,
    variables: JSON.stringify(["{{date}}", "{{assignee}}"]),
    lists: [
      {
        id: "list_research_planning",
        name: "📋 Planning",
        position: 0,
        color: "#94a3b8",
        emoji: "📋",
        tasks: [
          {
            id: "task_research_1",
            title: "📚 Literature review",
            description: "Gather 20-30 relevant papers and studies.",
            position: 0,
            emoji: "📚",
            coverColor: "#64748b",
            labels: JSON.stringify(["research", "reading"]),
          },
          {
            id: "task_research_2",
            title: "❓ Define research questions",
            description: "Formulate 3-5 key questions to investigate.",
            position: 1,
            emoji: "❓",
            coverColor: "#475569",
            labels: JSON.stringify(["planning", "methodology"]),
          },
          {
            id: "task_research_3",
            title: "📝 IRB approval application",
            description: "Submit ethics review if involving human subjects.",
            position: 2,
            emoji: "📝",
            coverColor: "#334155",
            labels: JSON.stringify(["compliance", "ethics"]),
          },
        ],
      },
      {
        id: "list_research_collection",
        name: "🔍 Data Collection",
        position: 1,
        color: "#3b82f6",
        emoji: "🔍",
        tasks: [
          {
            id: "task_research_4",
            title: "👥 Recruit participants",
            description: "Target: 50 participants by {{date}}. Assigned to {{assignee}}.",
            position: 0,
            emoji: "👥",
            coverColor: "#3b82f6",
            labels: JSON.stringify(["recruitment", "participants"]),
            variables: JSON.stringify({ date: "{{date}}", assignee: "{{assignee}}" }),
          },
          {
            id: "task_research_5",
            title: "📊 Conduct surveys/interviews",
            description: "Standardized questionnaire, 30 mins each.",
            position: 1,
            emoji: "📊",
            coverColor: "#2563eb",
            labels: JSON.stringify(["data-collection", "interviews"]),
          },
        ],
      },
      {
        id: "list_research_analysis",
        name: "📈 Analysis",
        position: 2,
        color: "#8b5cf6",
        emoji: "📈",
        tasks: [
          {
            id: "task_research_6",
            title: "🧮 Statistical analysis",
            description: "Run tests: t-test, ANOVA, regression (SPSS/R).",
            position: 0,
            emoji: "🧮",
            coverColor: "#7c3aed",
            labels: JSON.stringify(["statistics", "analysis"]),
          },
          {
            id: "task_research_7",
            title: "📉 Data visualization",
            description: "Create charts, graphs, tables for findings.",
            position: 1,
            emoji: "📉",
            coverColor: "#6d28d9",
            labels: JSON.stringify(["visualization", "results"]),
          },
        ],
      },
      {
        id: "list_research_writing",
        name: "✍️ Writing",
        position: 3,
        color: "#f59e0b",
        emoji: "✍️",
        tasks: [
          {
            id: "task_research_8",
            title: "📄 Draft manuscript",
            description: "Introduction, Methods, Results, Discussion.",
            position: 0,
            emoji: "📄",
            coverColor: "#d97706",
            labels: JSON.stringify(["writing", "manuscript"]),
          },
          {
            id: "task_research_9",
            title: "👀 Peer review",
            description: "Co-authors review and provide feedback.",
            position: 1,
            emoji: "👀",
            coverColor: "#ea580c",
            labels: JSON.stringify(["review", "collaboration"]),
          },
        ],
      },
      {
        id: "list_research_publication",
        name: "📰 Publication",
        position: 4,
        color: "#10b981",
        emoji: "📰",
        tasks: [
          {
            id: "task_research_10",
            title: "📮 Submit to journal",
            description: "Target: Journal of XYZ Research.",
            position: 0,
            emoji: "📮",
            coverColor: "#059669",
            labels: JSON.stringify(["publication", "submission"]),
          },
          {
            id: "task_research_11",
            title: "🎓 Conference presentation",
            description: "Present findings at annual conference.",
            position: 1,
            emoji: "🎓",
            coverColor: "#047857",
            labels: JSON.stringify(["conference", "presentation"]),
          },
        ],
      },
    ],
  },
  {
    id: "template_hiring_pipeline",
    name: "👔 Hiring Pipeline",
    description: "Track candidates through the recruitment process from application to offer.",
    category: "onboarding",
    icon: "👔",
    coverImage: "linear-gradient(135deg, #ffecd2 0%, #fcb69f 100%)",
    isPredefined: true,
    isPublic: true,
    usageCount: 0,
    rating: 0,
    variables: JSON.stringify(["{{assignee}}", "{{organization}}"]),
    lists: [
      {
        id: "list_hiring_applications",
        name: "📬 New Applications",
        position: 0,
        color: "#94a3b8",
        emoji: "📬",
        tasks: [
          {
            id: "task_hiring_1",
            title: "👨‍💻 John Smith - Senior Developer",
            description: "5 years experience, React/Node.js, strong portfolio.",
            position: 0,
            emoji: "👨‍💻",
            coverColor: "#64748b",
            labels: JSON.stringify(["developer", "senior"]),
          },
          {
            id: "task_hiring_2",
            title: "👩‍🎨 Sarah Lee - UX Designer",
            description: "3 years exp, Figma expert, B2B SaaS background.",
            position: 1,
            emoji: "👩‍🎨",
            coverColor: "#475569",
            labels: JSON.stringify(["designer", "mid-level"]),
          },
        ],
      },
      {
        id: "list_hiring_screening",
        name: "📞 Phone Screen",
        position: 1,
        color: "#3b82f6",
        emoji: "📞",
        tasks: [
          {
            id: "task_hiring_3",
            title: "👨‍💼 Mike Chen - Product Manager",
            description: "Scheduled with {{assignee}} for {{organization}} role.",
            position: 0,
            emoji: "👨‍💼",
            coverColor: "#3b82f6",
            labels: JSON.stringify(["pm", "screening"]),
            variables: JSON.stringify({ assignee: "{{assignee}}", organization: "{{organization}}" }),
          },
        ],
      },
      {
        id: "list_hiring_technical",
        name: "💻 Technical Interview",
        position: 2,
        color: "#8b5cf6",
        emoji: "💻",
        tasks: [
          {
            id: "task_hiring_4",
            title: "👩‍💻 Emily Wang - Frontend Engineer",
            description: "Take-home project: Build responsive dashboard.",
            position: 0,
            emoji: "👩‍💻",
            coverColor: "#7c3aed",
            labels: JSON.stringify(["engineer", "assessment"]),
          },
        ],
      },
      {
        id: "list_hiring_final",
        name: "🤝 Final Round",
        position: 3,
        color: "#f59e0b",
        emoji: "🤝",
        tasks: [
          {
            id: "task_hiring_5",
            title: "👨‍🔬 David Park - Data Scientist",
            description: "Meet with CTO and team leads.",
            position: 0,
            emoji: "👨‍🔬",
            coverColor: "#d97706",
            labels: JSON.stringify(["data-science", "final-round"]),
          },
        ],
      },
      {
        id: "list_hiring_offer",
        name: "✅ Offer Extended",
        position: 4,
        color: "#10b981",
        emoji: "✅",
        tasks: [
          {
            id: "task_hiring_6",
            title: "👩‍💼 Lisa Rodriguez - Marketing Manager",
            description: "Offer sent: $120k, equity, benefits. Awaiting response.",
            position: 0,
            emoji: "👩‍💼",
            coverColor: "#059669",
            labels: JSON.stringify(["marketing", "offer"]),
          },
        ],
      },
    ],
  },
  {
    id: "template_video_production",
    name: "🎬 Video Production",
    description: "Manage video projects from pre-production through post-production and distribution.",
    category: "custom",
    icon: "🎬",
    coverImage: "linear-gradient(135deg, #667eea 0%, #764ba2 100%)",
    isPredefined: true,
    isPublic: true,
    usageCount: 0,
    rating: 0,
    variables: JSON.stringify(["{{date}}", "{{assignee}}"]),
    lists: [
      {
        id: "list_video_preproduction",
        name: "📝 Pre-Production",
        position: 0,
        color: "#3b82f6",
        emoji: "📝",
        tasks: [
          {
            id: "task_video_1",
            title: "📜 Script writing",
            description: "Draft script with scene breakdowns and dialogue.",
            position: 0,
            emoji: "📜",
            coverColor: "#3b82f6",
            labels: JSON.stringify(["script", "writing"]),
          },
          {
            id: "task_video_2",
            title: "🎨 Storyboard creation",
            description: "Visual outline of key scenes and shots.",
            position: 1,
            emoji: "🎨",
            coverColor: "#2563eb",
            labels: JSON.stringify(["storyboard", "planning"]),
          },
          {
            id: "task_video_3",
            title: "📍 Location scouting",
            description: "Find 3 suitable filming locations. Assigned to {{assignee}}.",
            position: 2,
            emoji: "📍",
            coverColor: "#1d4ed8",
            labels: JSON.stringify(["location", "logistics"]),
            variables: JSON.stringify({ assignee: "{{assignee}}" }),
          },
        ],
      },
      {
        id: "list_video_production",
        name: "🎥 Production",
        position: 1,
        color: "#f59e0b",
        emoji: "🎥",
        tasks: [
          {
            id: "task_video_4",
            title: "🎬 Day 1 - Shoot opening scenes",
            description: "Location: Office. Call time: 8AM on {{date}}.",
            position: 0,
            emoji: "🎬",
            coverColor: "#f59e0b",
            labels: JSON.stringify(["filming", "day-1"]),
            variables: JSON.stringify({ date: "{{date}}" }),
          },
          {
            id: "task_video_5",
            title: "🎤 Record voiceover",
            description: "Book studio, hire voice actor, 2-hour session.",
            position: 1,
            emoji: "🎤",
            coverColor: "#d97706",
            labels: JSON.stringify(["audio", "voiceover"]),
          },
        ],
      },
      {
        id: "list_video_postproduction",
        name: "✂️ Post-Production",
        position: 2,
        color: "#8b5cf6",
        emoji: "✂️",
        tasks: [
          {
            id: "task_video_6",
            title: "🎞️ Video editing",
            description: "Cut, arrange clips, add transitions (Premiere Pro).",
            position: 0,
            emoji: "🎞️",
            coverColor: "#7c3aed",
            labels: JSON.stringify(["editing", "video"]),
          },
          {
            id: "task_video_7",
            title: "🎵 Music & sound design",
            description: "Add background music, sound effects, mix audio.",
            position: 1,
            emoji: "🎵",
            coverColor: "#6d28d9",
            labels: JSON.stringify(["audio", "music"]),
          },
          {
            id: "task_video_8",
            title: "🎨 Color grading",
            description: "Apply color correction and cinematic look.",
            position: 2,
            emoji: "🎨",
            coverColor: "#5b21b6",
            labels: JSON.stringify(["grading", "color"]),
          },
        ],
      },
      {
        id: "list_video_review",
        name: "👀 Review",
        position: 3,
        color: "#ec4899",
        emoji: "👀",
        tasks: [
          {
            id: "task_video_9",
            title: "🔍 Client feedback - Round 1",
            description: "Send draft for review, collect notes.",
            position: 0,
            emoji: "🔍",
            coverColor: "#db2777",
            labels: JSON.stringify(["review", "client"]),
          },
        ],
      },
      {
        id: "list_video_distribution",
        name: "🚀 Distribution",
        position: 4,
        color: "#10b981",
        emoji: "🚀",
        tasks: [
          {
            id: "task_video_10",
            title: "📺 Upload to YouTube",
            description: "Optimize title, description, tags, thumbnail.",
            position: 0,
            emoji: "📺",
            coverColor: "#059669",
            labels: JSON.stringify(["youtube", "publishing"]),
          },
          {
            id: "task_video_11",
            title: "📱 Social media clips",
            description: "Create 15s/30s/60s versions for Instagram, TikTok.",
            position: 1,
            emoji: "📱",
            coverColor: "#047857",
            labels: JSON.stringify(["social", "short-form"]),
          },
        ],
      },
    ],
  },
];

async function main() {
  console.log("🌱 Seeding additional board templates...");

  for (const template of additionalTemplates) {
    const { lists, ...templateData } = template;

    console.log(`   Creating template: ${template.name}`);

    await prisma.boardTemplate.create({
      data: {
        ...templateData,
        lists: {
          create: lists.map((list) => {
            const { tasks, ...listData } = list;
            return {
              ...listData,
              tasks: {
                create: tasks,
              },
            };
          }),
        },
      },
    });
  }

  console.log("✅ Successfully seeded 6 additional templates!");
  console.log("📊 Total templates: 12");
}

main()
  .catch((e) => {
    console.error("❌ Error seeding templates:", e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
